name: Romain Soufflet
markdown: redcarpet
highlighter: true

destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
exclude:     ['vendor', 'Makefile', 'README.md']
keep_files:  ['.git', '.svn']
